theme: jekyll-theme-minimal
title: Shraavya M C
description: MSc Bioinformatics & Genetic Epidemiology | Biotechnology Graduate | Bioinformatics & Genomic Data Analyst | NGS Variant Calling | Python & R | Statistical Genetics
